FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=http://localhost:8080
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

ARG VITE_WS_BASE_URL=http://localhost:8080
ENV VITE_WS_BASE_URL=$VITE_WS_BASE_URL

EXPOSE 5173

CMD ["npm", "run", "dev"]

